### post article success
POST http://localhost:3000/api/articles HTTP/1.1
content-type: application/json

{
  "title": "Как преодолеть творческий кризис.",
  "announce": "Творческий кризис посещает каждого человека, чем бы они ни занимался. Нет ничего сложнее для мозга, чем придумать новый дизайн или что приготовить на ужин. Подобные проблемы случаются и в творческих профессиях, и в личной жизни. В этой статье вы найдете способы преодоления творческого кризиса.",
  "description": "Вы всегда можете использовать эти способы для выхода из творческого кризиса: 1. Хороший отдых. 2. Физические нагрузки. 3. Переключение задач. 4. Мозговой штурм. 5. Советы друзей и знакомых. 6. Искусственное создание проблем для ощущения контраста. 7. Доработка и переделывание. 8. Смена обстановки. 9. Новые образы и новые впечатления. 10. Конкуренция.",
  "date": "2020-03-16 22:19:52",
  "category": ["За жизнь", "Веб-дизайн"]
}

### check new article
GET http://localhost:3000/api/articles/PXzYNq HTTP/1.1

### delete article
DELETE http://localhost:3000/api/articles/PXzYNq HTTP/1.1

### post article failed - missed offer ticket-name field
POST http://localhost:3000/api/articles/ HTTP/1.1
content-type: application/json

{
  "name": "Как преодолеть творческий кризис.",
  "announce": "Творческий кризис посещает каждого человека, чем бы они ни занимался. Нет ничего сложнее для мозга, чем придумать новый дизайн или что приготовить на ужин. Подобные проблемы случаются и в творческих профессиях, и в личной жизни. В этой статье вы найдете способы преодоления творческого кризиса.",
  "description": "Вы всегда можете использовать эти способы для выхода из творческого кризиса: 1. Хороший отдых. 2. Физические нагрузки. 3. Переключение задач. 4. Мозговой штурм. 5. Советы друзей и знакомых. 6. Искусственное создание проблем для ощущения контраста. 7. Доработка и переделывание. 8. Смена обстановки. 9. Новые образы и новые впечатления. 10. Конкуренция.",
  "date": "2020-03-16 22:19:52",
  "category": ["За жизнь", "Веб-дизайн"]
}

### post article failed - incorrect required fields count
POST http://localhost:3000/api/articles/ HTTP/1.1
content-type: application/json

{
  "title": "Как преодолеть творческий кризис.",
  "description": "Вы всегда можете использовать эти способы для выхода из творческого кризиса: 1. Хороший отдых. 2. Физические нагрузки. 3. Переключение задач. 4. Мозговой штурм. 5. Советы друзей и знакомых. 6. Искусственное создание проблем для ощущения контраста. 7. Доработка и переделывание. 8. Смена обстановки. 9. Новые образы и новые впечатления. 10. Конкуренция.",
  "date": "2020-03-16 22:19:52",
  "category": ["За жизнь", "Веб-дизайн"]
}

### delete article 404
DELETE http://localhost:3000/api/articles/TqZD3s HTTP/1.1
